services:
  postgres:
    image: postgres:latest
    container_name: trimly_db
    ports:
      - 6500:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres1234
      - POSTGRES_DB=trimly_db
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:


#version: '3'
#services:
#  trimly-api:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: trimly-api
#    ports:
#      - "8080:8080"